version: "3"
services: 
    #postgres database    
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    #Nginx
    simple-blog-api:
        depends_on:
           -  postgres
        image: nilanjana17maity/simple-blog
        build:
          context: .
          dockerfile: Dockerfile.prod
        ports:
            - "3000:3000"
        environment:
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=simple_blog_api    